appVersion: latest

statefulSet:
  name: bot
  image: ghcr.io/preparingforexams/hhh-diff-bot
  revisionHistoryLimit: 1
  requests:
    cpu: 50m
    memory: 50Mi

claim:
  size: 100Mi
  accessMode: ReadWriteOnce
  storageClass: longhorn-crypto

secret:
  name: secrets

configmap:
  name: hhh-diff-bot
  ageThresholdDays: 30

telegram:
  mainAdminIds:
    - 133399998
