namespace: telegram-bots

deployment:
  name: hhhdiffbot
  image: ghcr.io/preparingforexams/hhh-diff-bot:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: hhhdiffbot
  requests:
    cpu: 50m
    memory: 50Mi
  updateStrategy: Recreate

volume:
  name: hhhdiffbot-state
  path: /data

claim:
  name: hhhdiffbot-state
  size: 1Gi
  accessMode: ReadWriteOnce

secret:
  name: hhhdiffbot-telegram-token
  password: __TELEGRAM_TOKEN__
  bing:
    key: __BING_IMAGE_API_SEARCH_KEY__
  openai:
    key: __OPENAI_API_KEY__

configmap:
  name: hhh-diff-bot
  ageThresholdDays: 30

telegram:
  mainAdminIds:
    - 139656428
    - 133399998

cronjob:
  name: hhh-diff-bot-reminder
  image: ghcr.io/preparingforexams/hhh-diff-bot:__TAG__
  imagePullPolicy: Always
  command: [ 'python3' ]
  args: [ 'reminder.py' ]
  schedule: "0 20 * * 0"
  backoffLimit: 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  restartPolicy: Never
  labels:
    app: hhh-diff-bot-reminder
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi
