namespace: telegram-bots

deployment:
  name: hhhdiffbot
  image: ghcr.io/preparingforexams/hhh-diff-bot:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: hhhdiffbot
  requests:
    cpu: 50m
    memory: 50Mi
  updateStrategy: Recreate

volume:
  name: hhhdiffbot-state
  path: /data

claim:
  name: hhhdiffbot-state
  size: 1Gi
  accessMode: ReadWriteOnce

secret:
  name: hhhdiffbot-telegram-token
  password: __TELEGRAM_TOKEN__
  bing:
    key: __BING_IMAGE_API_SEARCH_KEY__

telegram:
  mainAdminIds:
    - 139656428
    - 133399998
