apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claim.name }}
spec:
  storageClassName: {{ .Values.claim.storageClass }}
  accessModes:
    - {{ .Values.claim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.claim.size }}
