---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-prep-diff-bot
    kind: ClusterSecretStore
  data:
    - secretKey: SENTRY_DSN
      remoteRef:
        key: "name:sentry-dsn"
        decodingStrategy: None
  dataFrom:
    - extract:
        key: "name:manual-secrets"
