---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secret.name }}
  dataFrom:
    - find:
        path: "DIFF_"
      rewrite:
        - regexp:
            source: "DIFF_(.+)"
            target: "$1"
