---
apiVersion: v1
kind: Service
metadata:
  name: bot
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bot
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.statefulSet.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: bot
  serviceName: bot
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: state
      spec:
        storageClassName: {{ .Values.claim.storageClass }}
        accessModes:
          - {{ .Values.claim.accessMode }}
        resources:
          requests:
            storage: {{ .Values.claim.size }}
  template:
    metadata:
      labels:
        app: bot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.longhorn.io/create-default-disk
                    operator: In
                    values:
                      - "true"
      containers:
        - name: app
          image: {{ .Values.statefulSet.image }}:{{ .Values.appVersion }}
          command:
            - sleep
            - infinity
          env:
            - name: MAIN_ADMIN_IDS
              value: {{ .Values.telegram.mainAdminIds | toJson | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          volumeMounts:
            - mountPath: "/data"
              name: state
          resources:
            requests:
              cpu: {{ .Values.statefulSet.requests.cpu }}
              memory: {{ .Values.statefulSet.requests.memory }}
