apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  CONFIGMAP_NAME: "{{ .Values.state.name }}"
  CONFIGMAP_NAMESPACE: "{{ .Values.namespace }}"
