apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  BOT_TOKEN: "{{ .Values.secret.password }}"
  BING_IMAGE_API_SEARCH_KEY: "{{ .Values.secret.bing.key }}"
  OPENAI_API_KEY: "{{ .Values.secret.openai.key }}"
