apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  BOT_TOKEN: "{{ .Values.secret.password }}"
  BING_IMAGE_API_SEARCH_KEY: "{{ .Values.secret.bing.key }}"
