name: Build/Publish docker image

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          raw_command: lint
      - uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          raw_command: lint --strict

  build_push_docker:
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-docker.yml@v3
    with:
      platform: "linux/arm64"
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    name: "Publish to k8s"
    container: ghcr.io/bjoernpetersen/helm:2.0.1
    runs-on: born-prep
    needs: [lint, build_push_docker]
    concurrency: production
    steps:
      - uses: actions/checkout@v4
      - run: sed -i -e "s/__TELEGRAM_TOKEN__/${{ secrets.BOT_TOKEN }}/g" values.yaml
      - run: sed -i -e "s/__BING_IMAGE_API_SEARCH_KEY__/${{ secrets.BING_IMAGE_API_SEARCH_KEY }}/g" values.yaml
      - run: sed -i -e "s/__OPENAI_API_KEY__/${{ secrets.OPENAI_API_KEY }}/g" values.yaml
      - run: sed -i -e "s/__TAG__/${GITHUB_SHA}/g" values.yaml
      - name: install helm chart
        uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          subcommand: upgrade
          ref: .
          release_name: hhhdiffbot
          namespace: hhh-diff-bot
          atomic: true
          install: true
          kubeconfig: ${{ secrets.BORN_KUBECONFIG_RAW }}
